# Generated by Django 4.2.21 on 2025-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0002_remove_person_father_remove_person_mother_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
